### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by julien** [yuchi/frontend-ng-loader-workspace#1]
Hi @yuchi ,

I followed your guide and like the idea of being able to use CJS in Liferay (although, I think mixing ES6 (`class`, `extends`, etc...) and CJS (`module.exports`) feels a bit strange) but I'm having trouble setting things up and wanted to share that with you.

### The bnd file

I first had to add this line to my **bnd.bnd** file:

`-includeresource: META-INF/resources/node_modules=node_modules`

Without that, I was unable to run `gradlew deploy` for my portlet. That might have to do with the location of the `package.json` file.

### Components

I created a simple component (`component.js`) under `src/main/resources/META-INF/resources/lib` and it has the following content:

```javascript
// component.js
var React = require('react');
var ReactDOM = require('react-dom');

class Component extends React.Component {
	render() {
		return <div>Hello {this.props.name}</div>;
	}
};

module.exports = Component;
```

I then created another component to "import" it, with the following content:

```javascript
// index.js
var React = require('react');
var ReactDOM = require('react-dom');
var Component = require('./component');

function render(config, wrapper) {
	return ReactDOM.render(
		React.createElement(Component, config),
		document.getElementById(wrapper));
}

module.exports = {render: render};
``` 

Then in my `view.jsp` file, I added a the following:

```jsp
<div id="<portlet:namespace />wrapper"> </div>

<aui:script>
System
    .import('quick-note-web/2.0.3')
    .then(function (MyModule) {
        MyModule.render({name: 'My component'}, '<portlet:namespace />wrapper');
    }, function (err) {
        console.error(err);
       // throws an error about "process" not being defined
   });
</aui:script>
```

As you can see, I replaced 
`'quick-note-web@2.0.3'` with `'quick-note-web/2.0.3'`
because using the `@` symbol was giving me a `404` error 

(Looking in the console, I saw that `System.paths` (or `SystemJS.paths`) are all defined with a `/` symbol separator)

With that done, I successfully deployed the portlet, but when I add it to a page, I get the following error:

```javascript
(index):439 Error: (SystemJS) ReferenceError: process is not defined(…)
```
Apparently this is not new with SystemJS, so I will keep on searching to see why this is happening.

If it can be usefull, for this example I was using the latest version of `react` and `react-dom` (`15.4.0`)

Thanks

**Comment by yuchi** [comment]
@julien Happy to have you on board.

The issue is incredibly easy to solve. What you are seeing is React searching for a *global* `process` object. It does it in order to have conditional behaviour:

```js
assert(1 == 3, 'Math is not working!');

function assert(guard, message) {
  if (!guard && process.env.NODE_ENV !== 'production') {
    throw new Error(message);
  }
}
```

It’s the standard way for having conditional code **in Node.js** and therefore has been shimmed by all bundlers ([Browserify does](https://github.com/substack/node-browserify#compatibility) and so [Webpack](http://webpack.github.io/docs/api-in-modules.html#process)). SystemJS is **not** a bundler, but a simple loader.

You need to shim it in order for stuff to work. Sorry for missing this out in the README.

To test it out (brutally):

```jsp
<aui:script >
  window.process = { env: {} };
</aui:script>
```

**Comment by yuchi** [comment]
Also a small important note is that for both Webpack and Browserify it‘s usual to use some dead-code-elimination tools so all appearances of `process.env.NODE_ENV` are automatically transformed to a constant expression (such as simply `"development”`). Then it can be easily identified as dead code. In fact…

```js
// …this…
if (process.env.NODE_ENV !== 'production') { }
// …becomes…
if ('development' !== 'production') { }
// …and then…
if (false) { }
// …and at the end is simply removed.

**Comment by yuchi** [comment]
([this small tool](https://github.com/hughsk/envify) is the one I’m talking about)

**Comment by julien** [comment]
@yuchi thanks for the quick reply and useful info.

Declaring process on the window did the trick.

**Comment by yuchi** [comment]
I re-read you issue and probably you are going to have issues with JSX. I suggest you to rewrite it by hand.

Remember that if you run the standard Liferay JS transpilation you‘d get an AMD module. AMD modules should work but I honestly haven’t tested it thoroughly.

**Comment by julien** [comment]
Yes, that's correct, thanks

**Comment by yuchi** [comment]
If you want to use JSX (you don’t need to) in your tests you can define a custom Gradle task that calls `babel` with a sane preset (`es2015`,`react` should do the job) on your sources.
You can also use `import` statements then!

If you have issues with gradle and custom tasks I’m sure @Ithildir can lend some help.

**Comment by yuchi** [comment]
Once you have the demo up and running just close the issue so I know that everything is ok ;)

I’ll update the quick documentation on the README asap.

**Comment by julien** [comment]
Hi again @yuchi,

Thanks I was able to get everything up and running from the start, I just wanted to give you some feedback, and your comments were much appreciated. 

Maybe you can label this as "feedback" or "question", it's a pitty GitHub doesn't let us do that by default instead of opening issues which aren't really "problematic". 

Anyway thanks again and talk to you soon.

**Comment by jbalsas** [comment]
Hey @yuchi, as you see we're trying to start getting some bearings as to what to expect and what can be introduced...

The `process` issue actually raises some flags... the extra step we wanted to take here (correct me if I'm wrong) is that one should be able to use any module in npm out of the box, no extra job required... If some (or many) of those target libraries actually require shimming process or bringing in other tool such as `Browserify`, `Webpack`... that kinda defeats the purpose, doesn't it? Creating your custom build is already possible, so you won't be needing the loader at all in that case...

**Comment by yuchi** [comment]
I just skipped doing it. For example I just add only few shins for standard mode modules (such as `assert`).

There are expected shims for globals too. `process` and `__dirname` For example.

The list is short and well defined. This is not something specific to React.

**Comment by jbalsas** [comment]
So, if we were to complete this and somehow make it available, would we also provide all the expected shims?

**Comment by yuchi** [comment]
The unopinionated answer is «yes for `__dirname` and `__filename`».
The opinionated answer «yes but also for `process`».

The Webpack/Browserify/share-frontend-js-stuff-on-npm community is more or less Node-inclined, and therefore we’re shimming the minimal Node environment on the browser more or less — `require` and Node-resolution-algorithm included.

**Comment by jbalsas** [comment]
Makes sense :)

**Comment by yuchi** [comment]
😗

**Comment by yuchi** [comment]
For built-in modules have a look here: https://github.com/substack/node-browserify/blob/master/lib/builtins.js
For standard globals there’s a package for that: https://www.npmjs.com/package/insert-module-globals (the list is https://github.com/substack/insert-module-globals/blob/master/index.js#L25)

**Comment by yuchi** [comment]
Almost forgot! There’s an excellent package that bundles all of them: https://www.npmjs.com/package/node-libs-browser

**Comment by julien** [comment]
Hi @yuchi ,

We're still having a look at this, but when trying to install many of the dependencies listed in this thread I get an error of this kind:

```
ERROR [Refresh Thread: Equinox Container: f0c8ff93-feb2-0016-1970-97de72259df6][frontend_packages_bundle_config_extender:97] Cannot parse dependency 
Unexpected token 'WILDCARD(x) at position 6', expecting '[NUMERIC(^(0|[1-9][0-9]*))]'
```

I'll let you know if I make any progress.

**Comment by yuchi** [comment]
That’s an issue on `java-semver`, the library I use to parse versions and version ranges.
It currently does’t provide full npm compatibility. See the issue zafarkhaja/jsemver#23 (and [my comment](https://github.com/zafarkhaja/jsemver/issues/23#issuecomment-215051905)).

Actually npm’s [semver implementation](https://www.npmjs.com/package/semver) follows [the spec](http://semver.org/) better and has a better range grammar IMHO.

In my opinion we should make our own implementation that passes all of npm’s semver tests.
@zafarkhaja’s is good but as he said himself it was not intended to provide that level of compatibility, and he’s not willing to accept the added complexity.

**Comment by yuchi** [comment]
As I see you are testing this little toy, I though it could be a good idea to give you a list of missing features. I’m creating an issue per missing feature.

Also I just add you as contributors.
