### ISSUE TITLE
Parity with npm’s semver

### ISSUE THREAD

**Issue by yuchi** [yuchi/frontend-ng-loader-workspace#2]
For semver parsing (versions and version ranges) we are actually using `com.github.zafarkhaja:java-semver` and its grammar is not a superset of npm’s.
See the discussion over zafarkhaja/jsemver#23.

We should make an implementation that passes all of [node-semver’s tests](https://github.com/npm/node-semver).

**Comment by yuchi** [comment]
@julien You can now have fun with metal too since we support the `M.m.b-prerelease` form for versions. 🎉

**Comment by yuchi** [comment]
Just to make it clear, it is now possible to do this:

```js
System.import('metal-dropdown/2.0.0').then(DropDownModule => {
  new DropDownModule.default({ … });
});
```

**Comment by julien** [comment]
@yuchi thanks, I'll take a look.
